"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ClipboardList, Plus, Search, Filter, CheckCircle2, Clock,
  AlertTriangle, X, Loader2, ChevronRight, User, Building2,
  Zap, FileText, RotateCcw, DollarSign, ChevronDown,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useAuth } from "@/context/AuthContext";
import { BRANCHES } from "@/lib/constants";

interface Task {
  _id: string;
  title: string;
  description?: string;
  type: string;
  priority: "low" | "medium" | "high" | "critical";
  status: "open" | "in_progress" | "completed" | "cancelled" | "snoozed";
  claimId?: string;
  claimNumber?: string;
  patientName?: string;
  branch?: string;
  medicalAid?: string;
  assignedToName?: string;
  dueDate?: string;
  completedAt?: string;
  isAutoGenerated: boolean;
  createdAt: string;
}

const PRIORITY_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  low:      { label: "Low",      color: "bg-gray-100 text-gray-600",    icon: "○" },
  medium:   { label: "Medium",   color: "bg-blue-100 text-blue-700",    icon: "◔" },
  high:     { label: "High",     color: "bg-amber-100 text-amber-700",  icon: "◑" },
  critical: { label: "Critical", color: "bg-red-100 text-red-700",      icon: "●" },
};

const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
  open:        { label: "Open",        color: "bg-blue-100 text-blue-800" },
  in_progress: { label: "In Progress", color: "bg-amber-100 text-amber-800" },
  completed:   { label: "Completed",   color: "bg-green-100 text-green-800" },
  cancelled:   { label: "Cancelled",   color: "bg-gray-100 text-gray-500" },
  snoozed:     { label: "Snoozed",     color: "bg-purple-100 text-purple-700" },
};

const TYPE_ICONS: Record<string, React.ElementType> = {
  follow_up:        Clock,
  escalation:       AlertTriangle,
  resubmission:     RotateCcw,
  finance_review:   DollarSign,
  payment_chase:    DollarSign,
  document_request: FileText,
  general:          ClipboardList,
};

const TYPE_LABELS: Record<string, string> = {
  follow_up: "Follow-up", escalation: "Escalation", resubmission: "Resubmission",
  finance_review: "Finance Review", branch_action: "Branch Action",
  payment_chase: "Payment Chase", document_request: "Document Request", general: "General",
};

function isOverdue(task: Task): boolean {
  if (!task.dueDate || ["completed", "cancelled"].includes(task.status)) return false;
  return new Date(task.dueDate) < new Date();
}

export default function TasksPage() {
  const { hasPermission } = useAuth();
  const router = useRouter();

  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("open");
  const [priorityFilter, setPriorityFilter] = useState("all");
  const [typeFilter, setTypeFilter] = useState("all");
  const [branchFilter, setBranchFilter] = useState("all");
  const [mineOnly, setMineOnly] = useState(false);

  const [showCreate, setShowCreate] = useState(false);
  const [createForm, setCreateForm] = useState({
    title: "", description: "", type: "general",
    priority: "medium", dueDate: "", branch: "", claimNumber: "",
  });
  const [creating, setCreating] = useState(false);

  const fetchTasks = useCallback(async () => {
    setLoading(true);
    const params = new URLSearchParams();
    if (statusFilter !== "all") params.set("status", statusFilter);
    if (priorityFilter !== "all") params.set("priority", priorityFilter);
    if (typeFilter !== "all") params.set("type", typeFilter);
    if (branchFilter !== "all") params.set("branch", branchFilter);
    if (mineOnly) params.set("mine", "true");
    params.set("page", String(page));
    params.set("limit", "25");

    const res = await fetch(`/api/v1/tasks?${params}`, { credentials: "include" });
    const json = await res.json();
    setTasks(json.data || []);
    setTotal(json.pagination?.total || 0);
    setTotalPages(json.pagination?.totalPages || 1);
    setLoading(false);
  }, [statusFilter, priorityFilter, typeFilter, branchFilter, mineOnly, page]);

  useEffect(() => { fetchTasks(); }, [fetchTasks]);

  const filtered = tasks.filter((t) =>
    !search || t.title.toLowerCase().includes(search.toLowerCase()) ||
    t.claimNumber?.toLowerCase().includes(search.toLowerCase()) ||
    t.patientName?.toLowerCase().includes(search.toLowerCase())
  );

  async function updateTaskStatus(id: string, status: string) {
    await fetch(`/api/v1/tasks/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ status }),
    });
    fetchTasks();
  }

  async function handleCreate() {
    if (!createForm.title.trim()) return;
    setCreating(true);
    await fetch("/api/v1/tasks", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify(createForm),
    });
    setCreating(false);
    setShowCreate(false);
    setCreateForm({ title: "", description: "", type: "general", priority: "medium", dueDate: "", branch: "", claimNumber: "" });
    fetchTasks();
  }

  const openCount = tasks.filter((t) => t.status === "open").length;
  const criticalCount = tasks.filter((t) => t.priority === "critical" && t.status !== "completed").length;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-5">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-gray-900 flex items-center gap-2">
              <ClipboardList className="w-5 h-5" />
              Tasks
            </h1>
            <p className="text-xs text-gray-400 mt-0.5">
              {openCount} open · {criticalCount > 0 && <span className="text-red-500">{criticalCount} critical</span>}
            </p>
          </div>
          <button
            onClick={() => setShowCreate(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-lg transition-colors"
          >
            <Plus className="w-4 h-4" /> New Task
          </button>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-6 space-y-4">
        {/* Filters */}
        <div className="flex gap-3 flex-wrap items-center">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search tasks..."
              className="pl-9 pr-4 py-2 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 w-56"
            />
          </div>

          {[
            { label: "Status", value: statusFilter, onChange: setStatusFilter, options: [
              { value: "all", label: "All statuses" },
              { value: "open", label: "Open" },
              { value: "in_progress", label: "In Progress" },
              { value: "completed", label: "Completed" },
              { value: "cancelled", label: "Cancelled" },
            ]},
            { label: "Priority", value: priorityFilter, onChange: setPriorityFilter, options: [
              { value: "all", label: "All priorities" },
              { value: "critical", label: "Critical" },
              { value: "high", label: "High" },
              { value: "medium", label: "Medium" },
              { value: "low", label: "Low" },
            ]},
            { label: "Type", value: typeFilter, onChange: setTypeFilter, options: [
              { value: "all", label: "All types" },
              ...Object.entries(TYPE_LABELS).map(([v, l]) => ({ value: v, label: l })),
            ]},
          ].map(({ label, value, onChange, options }) => (
            <select
              key={label}
              value={value}
              onChange={(e) => onChange(e.target.value)}
              className="px-3 py-2 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none"
            >
              {options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          ))}

          <label className="flex items-center gap-2 cursor-pointer text-sm text-gray-600">
            <input
              type="checkbox"
              checked={mineOnly}
              onChange={(e) => setMineOnly(e.target.checked)}
              className="w-4 h-4 rounded"
            />
            Mine only
          </label>
        </div>

        {/* Tasks list */}
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          {loading ? (
            <div className="py-20 text-center">
              <Loader2 className="w-6 h-6 text-gray-300 animate-spin mx-auto" />
            </div>
          ) : filtered.length === 0 ? (
            <div className="py-20 text-center">
              <ClipboardList className="w-10 h-10 text-gray-200 mx-auto mb-3" />
              <p className="text-gray-400 text-sm">No tasks found</p>
            </div>
          ) : (
            <div className="divide-y divide-gray-50">
              {filtered.map((task) => {
                const Icon = TYPE_ICONS[task.type] || ClipboardList;
                const overdue = isOverdue(task);
                const pc = PRIORITY_CONFIG[task.priority];
                const sc = STATUS_CONFIG[task.status];

                return (
                  <div
                    key={task._id}
                    className={cn(
                      "flex items-start gap-4 px-5 py-4 hover:bg-gray-50 transition-colors",
                      overdue && "bg-red-50/30 border-l-2 border-l-red-400"
                    )}
                  >
                    <div className={cn(
                      "w-9 h-9 rounded-xl flex items-center justify-center shrink-0 mt-0.5",
                      task.priority === "critical" ? "bg-red-100" :
                      task.priority === "high" ? "bg-amber-100" :
                      task.priority === "medium" ? "bg-blue-100" : "bg-gray-100"
                    )}>
                      <Icon className={cn(
                        "w-4 h-4",
                        task.priority === "critical" ? "text-red-600" :
                        task.priority === "high" ? "text-amber-600" :
                        task.priority === "medium" ? "text-blue-600" : "text-gray-500"
                      )} />
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1">
                          <p className={cn("font-medium text-sm", task.status === "completed" && "line-through text-gray-400")}>
                            {task.title}
                          </p>
                          {task.description && (
                            <p className="text-xs text-gray-400 mt-0.5 line-clamp-1">{task.description}</p>
                          )}
                          <div className="flex items-center gap-3 mt-1.5 flex-wrap">
                            <span className={cn("px-1.5 py-0.5 rounded-full text-[10px] font-semibold", pc.color)}>
                              {pc.label}
                            </span>
                            <span className={cn("px-1.5 py-0.5 rounded-full text-[10px] font-semibold", sc.color)}>
                              {sc.label}
                            </span>
                            <span className="text-[10px] text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded-full">
                              {TYPE_LABELS[task.type] || task.type}
                            </span>
                            {task.claimNumber && (
                              <Link href={task.claimId ? `/claims/${task.claimId}` : "#"}>
                                <span className="text-[10px] text-blue-600 hover:underline font-mono">{task.claimNumber}</span>
                              </Link>
                            )}
                            {task.branch && (
                              <span className="text-[10px] text-gray-400 flex items-center gap-1">
                                <Building2 className="w-2.5 h-2.5" />{task.branch}
                              </span>
                            )}
                            {task.dueDate && (
                              <span className={cn("text-[10px] flex items-center gap-1", overdue ? "text-red-500 font-semibold" : "text-gray-400")}>
                                <Clock className="w-2.5 h-2.5" />
                                {overdue ? "Overdue: " : "Due: "}
                                {new Date(task.dueDate).toLocaleDateString()}
                              </span>
                            )}
                            {task.isAutoGenerated && (
                              <span className="text-[10px] text-purple-500 bg-purple-50 px-1.5 py-0.5 rounded-full">Auto</span>
                            )}
                          </div>
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                          {task.status === "open" && (
                            <button
                              onClick={() => updateTaskStatus(task._id, "in_progress")}
                              className="text-xs px-2.5 py-1 bg-blue-50 text-blue-700 rounded-lg hover:bg-blue-100 transition-colors"
                            >
                              Start
                            </button>
                          )}
                          {task.status === "in_progress" && (
                            <button
                              onClick={() => updateTaskStatus(task._id, "completed")}
                              className="text-xs px-2.5 py-1 bg-green-50 text-green-700 rounded-lg hover:bg-green-100 transition-colors"
                            >
                              Complete
                            </button>
                          )}
                          {["open", "in_progress"].includes(task.status) && (
                            <button
                              onClick={() => updateTaskStatus(task._id, "cancelled")}
                              className="text-xs px-2.5 py-1 bg-gray-50 text-gray-500 rounded-lg hover:bg-gray-100 transition-colors"
                            >
                              Cancel
                            </button>
                          )}
                          {task.status === "completed" && (
                            <CheckCircle2 className="w-4 h-4 text-green-500" />
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {totalPages > 1 && (
            <div className="flex items-center justify-between px-5 py-3 border-t border-gray-100">
              <p className="text-xs text-gray-400">Page {page} of {totalPages} · {total} tasks</p>
              <div className="flex gap-2">
                <button disabled={page === 1} onClick={() => setPage((p) => p - 1)} className="px-3 py-1.5 text-xs border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-40">Previous</button>
                <button disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)} className="px-3 py-1.5 text-xs border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-40">Next</button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Create Task Modal */}
      {showCreate && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg">
            <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
              <h2 className="font-semibold text-gray-900">New Task</h2>
              <button onClick={() => setShowCreate(false)}><X className="w-5 h-5 text-gray-400" /></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-medium text-gray-600">Title *</label>
                <input
                  type="text"
                  value={createForm.title}
                  onChange={(e) => setCreateForm((p) => ({ ...p, title: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Task title..."
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-medium text-gray-600">Description</label>
                <textarea
                  value={createForm.description}
                  onChange={(e) => setCreateForm((p) => ({ ...p, description: e.target.value }))}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs font-medium text-gray-600">Type</label>
                  <select
                    value={createForm.type}
                    onChange={(e) => setCreateForm((p) => ({ ...p, type: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                  >
                    {Object.entries(TYPE_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-gray-600">Priority</label>
                  <select
                    value={createForm.priority}
                    onChange={(e) => setCreateForm((p) => ({ ...p, priority: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                  >
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                    <option value="critical">Critical</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-gray-600">Due Date</label>
                  <input
                    type="date"
                    value={createForm.dueDate}
                    onChange={(e) => setCreateForm((p) => ({ ...p, dueDate: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-medium text-gray-600">Branch</label>
                  <select
                    value={createForm.branch}
                    onChange={(e) => setCreateForm((p) => ({ ...p, branch: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                  >
                    <option value="">All branches</option>
                    {BRANCHES.map((b) => <option key={b} value={b}>{b}</option>)}
                  </select>
                </div>
              </div>
              <div className="space-y-1">
                <label className="text-xs font-medium text-gray-600">Claim Number (optional)</label>
                <input
                  type="text"
                  value={createForm.claimNumber}
                  onChange={(e) => setCreateForm((p) => ({ ...p, claimNumber: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                  placeholder="e.g. CLM-2026-RBH-00123"
                />
              </div>
            </div>
            <div className="flex gap-3 px-6 pb-6">
              <button
                onClick={handleCreate}
                disabled={creating || !createForm.title.trim()}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-lg disabled:opacity-50"
              >
                {creating && <Loader2 className="w-4 h-4 animate-spin" />}
                Create Task
              </button>
              <button onClick={() => setShowCreate(false)} className="px-4 py-2 border border-gray-200 text-sm rounded-lg hover:bg-gray-50">Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}