// FILE: lib/models/Task.ts

import mongoose, { Schema, Document, Model } from "mongoose";

export type TaskType =
  | "follow_up"
  | "escalation"
  | "resubmission"
  | "finance_review"
  | "branch_action"
  | "payment_chase"
  | "document_request"
  | "general";

export type TaskPriority = "low" | "medium" | "high" | "critical";
export type TaskStatus = "open" | "in_progress" | "completed" | "cancelled" | "snoozed";

export interface ITask extends Document {
  title: string;
  description?: string;
  type: TaskType;
  priority: TaskPriority;
  status: TaskStatus;
  claimId?: mongoose.Types.ObjectId;
  claimNumber?: string;
  patientId?: mongoose.Types.ObjectId;
  patientName?: string;
  branch?: string;
  medicalAid?: string;
  assignedTo?: mongoose.Types.ObjectId;
  assignedToName?: string;
  createdBy?: mongoose.Types.ObjectId;
  dueDate?: Date;
  completedAt?: Date;
  completedBy?: mongoose.Types.ObjectId;
  snoozedUntil?: Date;
  notes?: string;
  isAutoGenerated: boolean;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TaskSchema = new Schema<ITask>(
  {
    title:           { type: String, required: true, trim: true },
    description:     { type: String },
    type:            { type: String, required: true, enum: [
      "follow_up","escalation","resubmission","finance_review",
      "branch_action","payment_chase","document_request","general"
    ]},
    priority:        { type: String, enum: ["low","medium","high","critical"], default: "medium" },
    status:          { type: String, enum: ["open","in_progress","completed","cancelled","snoozed"], default: "open" },
    claimId:         { type: Schema.Types.ObjectId, ref: "Claim" },
    claimNumber:     { type: String },
    patientId:       { type: Schema.Types.ObjectId, ref: "Patient" },
    patientName:     { type: String },
    branch:          { type: String },
    medicalAid:      { type: String },
    assignedTo:      { type: Schema.Types.ObjectId, ref: "User" },
    assignedToName:  { type: String },
    createdBy:       { type: Schema.Types.ObjectId, ref: "User" },
    dueDate:         { type: Date },
    completedAt:     { type: Date },
    completedBy:     { type: Schema.Types.ObjectId, ref: "User" },
    snoozedUntil:    { type: Date },
    notes:           { type: String },
    isAutoGenerated: { type: Boolean, default: false },
    isDeleted:       { type: Boolean, default: false },
  },
  { timestamps: true }
);

TaskSchema.index({ status: 1 });
TaskSchema.index({ priority: 1 });
TaskSchema.index({ claimId: 1 });
TaskSchema.index({ assignedTo: 1 });
TaskSchema.index({ dueDate: 1 });
TaskSchema.index({ type: 1 });
TaskSchema.index({ branch: 1 });
TaskSchema.index({ isDeleted: 1 });

const Task: Model<ITask> =
  mongoose.models.Task || mongoose.model<ITask>("Task", TaskSchema);

export default Task;