// FILE: app/api/v1/tasks/route.ts

import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/auth/middleware";
import { connectDB } from "@/lib/mongodb";
import Task from "@/lib/models/Task";
import AuditLog from "@/lib/models/AuditLog";
import { toApiError, ValidationError } from "@/lib/errors";
import { getAuditContext } from "@/lib/auth/middleware";
import mongoose from "mongoose";

// GET /api/v1/tasks
export const GET = withAuth(async (req, context) => {
  try {
    await connectDB();
    const { user } = context as any;
    const { searchParams } = new URL(req.url);

    const filter: any = { isDeleted: false };

    const status = searchParams.get("status");
    if (status && status !== "all") filter.status = status;

    const type = searchParams.get("type");
    if (type && type !== "all") filter.type = type;

    const priority = searchParams.get("priority");
    if (priority && priority !== "all") filter.priority = priority;

    const branch = searchParams.get("branch");
    if (branch && branch !== "all") filter.branch = branch;
    else if (user.role === "branch_manager" && user.branch) filter.branch = user.branch;

    // Assigned to me
    if (searchParams.get("mine") === "true") {
      filter.assignedTo = new mongoose.Types.ObjectId(user.userId);
    }

    const page = parseInt(searchParams.get("page") || "1");
    const limit = Math.min(parseInt(searchParams.get("limit") || "50"), 200);
    const skip = (page - 1) * limit;

    const [data, total] = await Promise.all([
      Task.find(filter)
        .sort({ priority: -1, dueDate: 1, createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Task.countDocuments(filter),
    ]);

    return NextResponse.json({
      success: true,
      data,
      pagination: {
        total, page, limit,
        totalPages: Math.ceil(total / limit),
        hasNext: page * limit < total,
        hasPrev: page > 1,
      },
    });
  } catch (error) {
    const apiError = toApiError(error);
    return NextResponse.json(apiError, { status: apiError.statusCode });
  }
});

// POST /api/v1/tasks
export const POST = withAuth(async (req, context) => {
  try {
    await connectDB();
    const { user } = context as any;
    const body = await req.json();
    const auditCtx = getAuditContext(req, user);

    if (!body.title?.trim()) {
      throw new ValidationError("Task title is required");
    }
    if (!body.type) {
      throw new ValidationError("Task type is required");
    }

    const task = await Task.create({
      ...body,
      createdBy: new mongoose.Types.ObjectId(user.userId),
      isAutoGenerated: false,
    });

    await AuditLog.create({
      action: "CREATE",
      entityType: "Task",
      entityId: task._id,
      entityLabel: task.title,
      newValues: { type: task.type, priority: task.priority },
      ...auditCtx,
    });

    return NextResponse.json({ success: true, data: task }, { status: 201 });
  } catch (error) {
    const apiError = toApiError(error);
    return NextResponse.json(apiError, { status: apiError.statusCode });
  }
});