// FILE: lib/automation/escalation.engine.ts
// Handles auto-escalation of approved claims unpaid > 30 days
// and pending claims > 60 days

import { connectDB } from "@/lib/mongodb";
import Claim from "@/lib/models/Claim";
import Task from "@/lib/models/Task";
import User from "@/lib/models/User";
import AuditLog from "@/lib/models/AuditLog";
import { NotificationService } from "@/lib/services/notification.service";
import mongoose from "mongoose";

export interface EscalationResult {
  processed: number;
  escalated: number;
  tasksCreated: number;
  notified: number;
  errors: string[];
}

export class EscalationEngine {
  // Rules: approved & unpaid > 30 days → escalate
  //        pending > 60 days → escalate
  static async run(): Promise<EscalationResult> {
    await connectDB();

    const result: EscalationResult = {
      processed: 0,
      escalated: 0,
      tasksCreated: 0,
      notified: 0,
      errors: [],
    };

    const now = new Date();
    const d30 = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const d60 = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

    try {
      // Claims to escalate
      const toEscalate = await Claim.find({
        isDeleted: false,
        status: { $in: ["approved", "pending", "partial"] },
        priority: { $ne: "critical" },
        $or: [
          // Approved but unpaid > 30 days
          { status: "approved", submissionDate: { $lte: d30 } },
          // Pending > 60 days
          { status: "pending", submissionDate: { $lte: d60 } },
          // Partial balance > 30 days
          { status: "partial", submissionDate: { $lte: d30 } },
        ],
      }).lean();

      result.processed = toEscalate.length;

      const financeUsers = await User.find({
        role: { $in: ["finance", "super_admin"] },
        active: true,
        isDeleted: false,
      }).lean();
      const financeIds = financeUsers.map((u) => (u._id as any).toString());

      for (const claim of toEscalate) {
        try {
          const claimId = (claim._id as any).toString();
          const daysOut = Math.floor(
            (now.getTime() - new Date(claim.submissionDate).getTime()) / 86400000
          );

          // Escalate the claim
          await Claim.findByIdAndUpdate(claimId, {
            $set: {
              priority: "critical",
              escalatedAt: now,
              escalationReason: `Auto-escalated: ${claim.status} for ${daysOut} days`,
            },
            $push: {
              history: {
                changedAt: now,
                previousStatus: claim.status,
                newStatus: claim.status, // Status unchanged — only priority elevated
                action: "ESCALATION",
                note: `Priority escalated to critical after ${daysOut} days`,
              },
            },
          });

          result.escalated++;

          // Audit
          await AuditLog.create({
            action: "ESCALATION",
            entityType: "Claim",
            entityId: claimId,
            entityLabel: claim.claimNumber,
            newValues: { priority: "critical", daysOutstanding: daysOut },
            description: `Auto-escalation by EscalationEngine`,
            success: true,
          });

          // Create escalation task if not exists
          const existingEscTask = await Task.findOne({
            claimId: new mongoose.Types.ObjectId(claimId),
            type: "escalation",
            status: { $in: ["open", "in_progress"] },
          });

          if (!existingEscTask) {
            await Task.create({
              title: `URGENT — ${claim.claimNumber}: ${claim.patientName} (${daysOut}d)`,
              description: `${claim.status.toUpperCase()} claim for ${daysOut} days. ${claim.medicalAid} has not responded. Immediate action required.`,
              type: "escalation",
              priority: "critical",
              status: "open",
              claimId: new mongoose.Types.ObjectId(claimId),
              claimNumber: claim.claimNumber,
              patientName: claim.patientName,
              branch: claim.branch,
              medicalAid: claim.medicalAid,
              dueDate: now,
              isAutoGenerated: true,
            });
            result.tasksCreated++;
          }

          // Notify finance
          if (financeIds.length > 0) {
            await NotificationService.broadcast(financeIds, {
              type: "escalation",
              title: "🚨 Claim Escalated — Urgent",
              message: `${claim.claimNumber} (${claim.patientName}) — ${daysOut} days ${claim.status}. Requires immediate finance action.`,
              claimId: claimId,
              claimNumber: claim.claimNumber,
              priority: "critical",
              expiresAt: new Date(now.getTime() + 7 * 86400000),
            });
            result.notified += financeIds.length;
          }
        } catch (err: any) {
          result.errors.push(`${claim.claimNumber}: ${err.message}`);
        }
      }
    } catch (err: any) {
      result.errors.push(`Engine error: ${err.message}`);
    }

    return result;
  }
}