// FILE: lib/automation/followup.engine.ts
// Scans overdue claims each morning and creates follow-up tasks + notifications

import { connectDB } from "@/lib/mongodb";
import Claim from "@/lib/models/Claim";
import Task from "@/lib/models/Task";
import User from "@/lib/models/User";
import { NotificationService } from "@/lib/services/notification.service";
import mongoose from "mongoose";

export interface FollowUpResult {
  claimsScanned: number;
  tasksCreated: number;
  notificationsSent: number;
  escalated: number;
  errors: string[];
}

export class FollowUpEngine {
  static async run(): Promise<FollowUpResult> {
    await connectDB();

    const result: FollowUpResult = {
      claimsScanned: 0,
      tasksCreated: 0,
      notificationsSent: 0,
      escalated: 0,
      errors: [],
    };

    try {
      const now = new Date();
      const d30 = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
      const d60 = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

      // Get all outstanding claims where follow-up is due
      const dueClaims = await Claim.find({
        status: { $in: ["pending", "approved", "partial"] },
        isDeleted: false,
        $or: [
          { followUpDate: { $lte: now } },
          {
            followUpDate: { $exists: false },
            submissionDate: { $lte: d30 },
          },
        ],
      }).lean();

      result.claimsScanned = dueClaims.length;

      // Get finance users to notify
      const financeUsers = await User.find({
        role: { $in: ["finance", "super_admin"] },
        active: true,
        isDeleted: false,
      }).lean();
      const financeUserIds = financeUsers.map((u) => (u._id as any).toString());

      for (const claim of dueClaims) {
        try {
          const claimId = (claim._id as any).toString();
          const daysOut = Math.floor(
            (now.getTime() - new Date(claim.submissionDate).getTime()) /
              (1000 * 60 * 60 * 24)
          );

          // Check if an open follow-up task already exists for this claim
          const existingTask = await Task.findOne({
            claimId: new mongoose.Types.ObjectId(claimId),
            type: "follow_up",
            status: { $in: ["open", "in_progress"] },
            isDeleted: false,
          });

          if (!existingTask) {
            const priority =
              daysOut >= 60 ? "critical" : daysOut >= 30 ? "high" : "medium";

            await Task.create({
              title: `Follow-up: ${claim.patientName} — ${claim.claimNumber}`,
              description: `Claim ${claim.claimNumber} has been outstanding for ${daysOut} days. Follow up with ${claim.medicalAid}.`,
              type: "follow_up",
              priority,
              status: "open",
              claimId: new mongoose.Types.ObjectId(claimId),
              claimNumber: claim.claimNumber,
              patientName: claim.patientName,
              branch: claim.branch,
              medicalAid: claim.medicalAid,
              dueDate: now,
              isAutoGenerated: true,
            });

            result.tasksCreated++;
          }

          // Auto-escalate if 60+ days
          if (daysOut >= 60 && claim.status !== "escalated") {
            await Claim.findByIdAndUpdate(claimId, {
              status: "escalated",
              priority: "critical",
              escalatedAt: now,
              escalationReason: `Auto-escalated: claim outstanding for ${daysOut} days`,
              $push: {
                history: {
                  changedAt: now,
                  previousStatus: claim.status,
                  newStatus: "escalated",
                  action: "ESCALATION",
                  note: `Auto-escalated after ${daysOut} days outstanding`,
                },
              },
            });

            // Create escalation task
            await Task.create({
              title: `ESCALATED: ${claim.patientName} — ${claim.claimNumber} (${daysOut}d)`,
              description: `URGENT: Claim ${claim.claimNumber} auto-escalated after ${daysOut} days. Immediate finance action required.`,
              type: "escalation",
              priority: "critical",
              status: "open",
              claimId: new mongoose.Types.ObjectId(claimId),
              claimNumber: claim.claimNumber,
              patientName: claim.patientName,
              branch: claim.branch,
              medicalAid: claim.medicalAid,
              dueDate: now,
              isAutoGenerated: true,
            });

            result.escalated++;

            // Notify finance team
            if (financeUserIds.length > 0) {
              await NotificationService.broadcast(financeUserIds, {
                type: "escalation",
                title: "⚠️ Claim Auto-Escalated",
                message: `${claim.claimNumber} (${claim.patientName}) has been escalated after ${daysOut} days outstanding with ${claim.medicalAid}.`,
                claimId: claimId,
                claimNumber: claim.claimNumber,
                priority: "critical",
                expiresAt: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
              });
              result.notificationsSent += financeUserIds.length;
            }
          } else if (daysOut >= 30) {
            // Send follow-up notification
            if (financeUserIds.length > 0) {
              await NotificationService.broadcast(financeUserIds, {
                type: "follow_up_due",
                title: "⏰ Follow-up Required",
                message: `${claim.claimNumber} (${claim.patientName}) — ${daysOut} days outstanding with ${claim.medicalAid}. Follow up today.`,
                claimId: claimId,
                claimNumber: claim.claimNumber,
                priority: daysOut >= 45 ? "high" : "medium",
                expiresAt: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
              });
              result.notificationsSent += financeUserIds.length;
            }
          }
        } catch (claimError: any) {
          result.errors.push(
            `Claim ${claim.claimNumber}: ${claimError.message}`
          );
        }
      }
    } catch (error: any) {
      result.errors.push(`Engine error: ${error.message}`);
    }

    return result;
  }
}